describe('home page', () => {
  it('home page visibility', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[data-cy="title"]').should('be.visible')
    cy.get('[data-cy="logo"]').should('be.visible')
    cy.get('[data-cy="orderOnlineLink"]').should('be.visible')
    cy.get('[data-cy="seeTheMenuLink"]').should('be.visible')
    cy.get('[data-cy="svgBtn"]').should('be.visible')
    cy.get('[data-cy="hamburgerOptions"]').should('not.visible')
    cy.get('[data-cy="facebookLink"]').should('be.visible')
    cy.get('[data-cy="backgroundImageOne"]').should('be.visible')
    cy.get('[data-cy="facebookLink"]').should('be.visible')
    cy.get('[data-cy="instagramLink"]').should('be.visible')
    cy.get('[data-cy="twitterLink"]').should('be.visible')
    cy.get('[data-cy="infoHeader"]').should('be.visible')
    cy.get('[data-cy="infoParagraph"]').should('be.visible')
    cy.get('[data-cy="hotDogImage"]').should('be.visible')
    cy.get('[data-cy="hotDogDescription"]').should('be.visible')
    cy.get('[data-cy="checkOurMenuBtn"]').should('be.visible')
    cy.get('[data-cy="backgroundImageTwo"]').should('be.visible')
    cy.get('[data-cy="stayInTouchDiv"]').contains('STAY IN TOUCH!')
  })
})